data:
  datafile: '/arc/home/aydanmckay/bprp_mae/final_model/pt_testing/10M_pretrain_data0622.h5'
  valid_keys: ['sslset11_part0','sslset14_part0','sslset2_part0','sslset5_part0','sslset20_part0']
  feature_cols: ['W1','W2','G','BP','RP','bp_1','bp_2','bp_3','bp_4','bp_5','bp_6','bp_7','bp_8','bp_9',
                 'bp_10','bp_11','bp_12','bp_13','bp_14','bp_15','bp_16','bp_17','bp_18','bp_19','bp_20',
                 'bp_21','bp_22','bp_23','bp_24','bp_25','bp_26','bp_27','bp_28','bp_29','bp_30','bp_31',
                 'bp_32','bp_33','bp_34','bp_35','bp_36','bp_37','bp_38','bp_39','bp_40','bp_41','bp_42',
                 'bp_43','bp_44','bp_45','bp_46','bp_47','bp_48','bp_49','bp_50','bp_51','bp_52','bp_53',
                 'bp_54','bp_55','rp_1','rp_2','rp_3','rp_4','rp_5','rp_6','rp_7','rp_8','rp_9','rp_10',
                 'rp_11','rp_12','rp_13','rp_14','rp_15','rp_16','rp_17','rp_18','rp_19','rp_20','rp_21',
                 'rp_22','rp_23','rp_24','rp_25','rp_26','rp_27','rp_28','rp_29','rp_30','rp_31','rp_32',
                 'rp_33','rp_34','rp_35','rp_36','rp_37','rp_38','rp_39','rp_40','rp_41','rp_42','rp_43',
                 'rp_44','rp_45','rp_46','rp_47','rp_48','rp_49','rp_50','rp_51','rp_52','rp_53','rp_54',
                 'rp_55','U_SMSS','V_SMSS','G_SMSS','R_SMSS','I_SMSS','Z_SMSS','U_SDSS','G_SDSS','R_SDSS',
                 'I_SDSS','Z_SDSS','G_PS1','R_PS1','I_PS1','Z_PS1','Y_PS1','J','H','KS','PARALLAX','EBV',
                 'pmra','pmdec']
  error_cols: ['W1','W2','G','BP','RP','bp_1','bp_2','bp_3','bp_4','bp_5','bp_6','bp_7','bp_8','bp_9',
               'bp_10','bp_11','bp_12','bp_13','bp_14','bp_15','bp_16','bp_17','bp_18','bp_19','bp_20',
               'bp_21','bp_22','bp_23','bp_24','bp_25','bp_26','bp_27','bp_28','bp_29','bp_30','bp_31',
               'bp_32','bp_33','bp_34','bp_35','bp_36','bp_37','bp_38','bp_39','bp_40','bp_41','bp_42',
               'bp_43','bp_44','bp_45','bp_46','bp_47','bp_48','bp_49','bp_50','bp_51','bp_52','bp_53',
               'bp_54','bp_55','rp_1','rp_2','rp_3','rp_4','rp_5','rp_6','rp_7','rp_8','rp_9','rp_10',
               'rp_11','rp_12','rp_13','rp_14','rp_15','rp_16','rp_17','rp_18','rp_19','rp_20','rp_21',
               'rp_22','rp_23','rp_24','rp_25','rp_26','rp_27','rp_28','rp_29','rp_30','rp_31','rp_32',
               'rp_33','rp_34','rp_35','rp_36','rp_37','rp_38','rp_39','rp_40','rp_41','rp_42','rp_43',
               'rp_44','rp_45','rp_46','rp_47','rp_48','rp_49','rp_50','rp_51','rp_52','rp_53','rp_54',
               'rp_55','U_SMSS','V_SMSS','G_SMSS','R_SMSS','I_SMSS','Z_SMSS','U_SDSS','G_SDSS','R_SDSS',
               'I_SDSS','Z_SDSS','G_PS1','R_PS1','I_PS1','Z_PS1','Y_PS1','J','H','KS','PARALLAX','EBV',
               'pmra','pmdec']
  recon_cols: ['W1','W2','G','BP','RP','bp_1','bp_2','bp_3','bp_4','bp_5','bp_6','bp_7','bp_8','bp_9',
               'bp_10','bp_11','bp_12','bp_13','bp_14','bp_15','bp_16','bp_17','bp_18','bp_19','bp_20',
               'bp_21','bp_22','bp_23','bp_24','bp_25','bp_26','bp_27','bp_28','bp_29','bp_30','bp_31',
               'bp_32','bp_33','bp_34','bp_35','bp_36','bp_37','bp_38','bp_39','bp_40','bp_41','bp_42',
               'bp_43','bp_44','bp_45','bp_46','bp_47','bp_48','bp_49','bp_50','bp_51','bp_52','bp_53',
               'bp_54','bp_55','rp_1','rp_2','rp_3','rp_4','rp_5','rp_6','rp_7','rp_8','rp_9','rp_10',
               'rp_11','rp_12','rp_13','rp_14','rp_15','rp_16','rp_17','rp_18','rp_19','rp_20','rp_21',
               'rp_22','rp_23','rp_24','rp_25','rp_26','rp_27','rp_28','rp_29','rp_30','rp_31','rp_32',
               'rp_33','rp_34','rp_35','rp_36','rp_37','rp_38','rp_39','rp_40','rp_41','rp_42','rp_43',
               'rp_44','rp_45','rp_46','rp_47','rp_48','rp_49','rp_50','rp_51','rp_52','rp_53','rp_54',
               'rp_55','U_SMSS','V_SMSS','G_SMSS','R_SMSS','I_SMSS','Z_SMSS','U_SDSS','G_SDSS','R_SDSS',
               'I_SDSS','Z_SDSS','G_PS1','R_PS1','I_PS1','Z_PS1','Y_PS1','J','H','KS']
  ft_datafile: '/arc/projects/k-pop/catalogues/andrae2023/ftset_spec_ga_0602_realmags.fits'
  classes: ['teff','e_teff','logg','e_logg','fe_h','e_fe_h','alpha','e_alpha','age','e_age']

model:
  layer_dims: [2048, 2048, 1024, 1024, 512, 512, 256, 256]
  pt_activ_func: 'elu'
  norm: 'layer'
  rtdl_embed: 16
  # decoder_dims: [256, 512, 1024]  # Optional: asymmetric decoder (default: mirrors encoder)
  saved_weights: '/arc/home/aydanmckay/bprp_mae/.model_instances/checkpoint_60_fullmodelrealmags0605.pth'

training:
  xp_masking_ratio: 0.9
  m_masking_ratio: 0.6
  lr: 0.00001
  weight_decay: 0.00001
  lasso: 0
  optimizer: 'adamw'
  loss_fn: 'mae'
  mini_batch_size: 1024
  epochs: 100

finetuning:
  num_epochs: 101
  mini_batch: 512 
  linearprobe: false
  mask: true
  multitask: true
  rncloss: false
  lr: 0.0001
  opt: 'adamw'
  activ: 'relu'
  l2: 0.0
  lf: 'quantile'
  pert_features: true
  pert_labels: false
  ensemble: false
  seed: 42
  pert_seed: 42
  ensemble_path: 'finetuning-checkpoint-here.pth'

saving:
  model_str: 'masked_stellar_autoencoder_ft_10M.pth'
  log_file: 'finetune_msa_100_epoch.log'
  checkpoint_interval: 50